apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-scale-test-g5
  version: "1.30"
  region: us-west-2
  tags:
    karpenter.sh/discovery: do-eks-yaml

availabilityZones:
  - us-west-2a
  - us-west-2b
  - us-west-2c
  - us-west-2d

iam:
  withOIDC: true
