apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: xin-eks-1-30-c5
  version: "1.30"
  region: us-west-2
  tags:
    karpenter.sh/discovery: do-eks-yaml

availabilityZones:
  - us-west-2a
  - us-west-2b
  - us-west-2c
  - us-west-2d

managedNodeGroups:

  - name: sys
    instanceType: m5.2xlarge
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        cloudWatch: true
    ssh:
      publicKeyName: xwnamz-watcher-alpha
 
  - name: c5
    instanceType: c5.9xlarge
    instancePrefix: c5
    privateNetworking: true
    availabilityZones: ["us-west-2a", "us-west-2b", "us-west-2c", "us-west-2d"]
    efaEnabled: false
    minSize: 0
    desiredCapacity: 3
    maxSize: 10
    volumeSize: 100
    iam:
      withAddonPolicies:
        cloudWatch: true
        ebs: true
        efs: true
        fsx: true
    ssh:
      publicKeyName: xwnamz-watcher-alpha

  - name: trn1
    instanceType: trn1.32xlarge
    amiFamily: AmazonLinux2
    instancePrefix: trn1
    privateNetworking: true
    availabilityZones: ["us-west-2d"]
    efaEnabled: true
    minSize: 0
    desiredCapacity: 1
    maxSize: 2
    volumeSize: 100
    iam:
      withAddonPolicies:
        cloudWatch: true
        ebs: true
        efs: true
        fsx: true
    ssh:
      publicKeyName: xwnamz-watcher-alpha

iam:
  withOIDC: true