apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: xin-eks-1-29-trn
  version: "1.29"
  region: us-west-2
  tags:
    karpenter.sh/discovery: do-eks-yaml

availabilityZones:
  - us-west-2b
  - us-west-2d

managedNodeGroups:

  - name: sys
    instanceType: m5.2xlarge
    desiredCapacity: 1
    iam:
      withAddonPolicies:
        cloudWatch: true
 
  - name: worker-trn1
    instanceType: trn1.32xlarge
    instancePrefix: trn1
    privateNetworking: true
    availabilityZones: ["us-west-2b", "us-west-2d"]
    efaEnabled: false
    minSize: 0
    desiredCapacity: 2
    maxSize: 10
    volumeSize: 100
    iam:
      withAddonPolicies:
        cloudWatch: true
        ebs: true
        efs: true
        fsx: true

iam:
  withOIDC: true
