apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-watcher
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: job-watcher-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:job-watcher
subjects:
  - kind: ServiceAccount
    name: job-watcher
    namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:job-watcher
rules:
- apiGroups:
    - ""
  resources:
    - nodes
    - nodes/status
    - pods
    - pods/status
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - nodes
    - nodes/status
  verbs:
    - patch
- apiGroups:
    - ""
  resources:
    - nodes
  verbs:
    - delete
- apiGroups:
    - ""
    - events.k8s.io
  resources:
    - events
  verbs:
    - create
    - patch
    - update
- apiGroups:
    - kubeflow.org
  resources:
    - pytorchjobs
    - pytorchjobs/status
  verbs:
    - get
    - list
    - watch
    - create
    - delete
    - patch
    - update
    - describe