apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: job-watcher
  namespace: kube-system
  labels:
    app: job-watcher
spec:
  selector:
    matchLabels:
      app: job-watcher
  template:
    metadata:
      labels:
        app: job-watcher
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux

      containers:
        - name: hyperpod-job-watcher
          args:
          image: 590184049168.dkr.ecr.us-west-2.amazonaws.com/hyperpod-job-watcher:xwnamz
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 2
              memory: 2Gi
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          volumeMounts:
            - name: log
              mountPath: /var/log
              readOnly: true
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
      serviceAccountName: job-watcher
      volumes:
        - name: log
          # Config `log` to your system log directory
          hostPath:
            path: /var/log/
        - name: localtime
          hostPath:
            path: /etc/localtime
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists